### ISSUE TITLE
Fix formule GitHub Markdown

### ISSUE THREAD

**Issue by TryKatChup** [TryKatChup/sicurezza-informazione-M#30]
Occorre utilizzare una notazione, come questa: ![formula](https://render.githubusercontent.com/render/math?math=\color{red}\large\K_{(A-kdc)})

Se no si fa fatica a leggere :(

**Comment by dariodenardi** [comment]
Oki facciamo come dici tu però ricordati di inserire doppia immagine per la doppia modalità (modifica questo messaggio e prendi il codice)

![formula](https://render.githubusercontent.com/render/math?math=\color{black}\large\K_{(A-kdc)}#gh-light-mode-only)
![formula](https://render.githubusercontent.com/render/math?math=\color{white}\large\K_{(A-kdc)}#gh-dark-mode-only)

**Comment by lnwor** [comment]
Le formule in quel modo si farebbero con mathjax, circondando la formula con dollari, tipo così: $formula$

Il problema è che il la preview da github non lo supporta, quindi il meglio che si può fare è mettere gli apici/pedici (li ho messi più o meno dappertutto). Se non vi viene in mente un modo migliore si potrebbe chiudere l'issue
